artifact_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source: 1HclwA9zvctv5pUZWrwHn70P51OOuYNqy 
  local_data_file : artifacts/data_ingestion/dog-breed-identification.zip
  unzip_dir: artifacts/data_ingestion


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model : artifacts/prepare_base_model/base_model.h5
  base_model_updated : artifacts/prepare_base_model/base_model_updated.h5


callbacks:
  root_dir: artifacts/callbacks
  model_checkpoint_filepath: artifacts/callbacks/checkpoints/model_checkpoint.h5
  tensorboard_dir: artifacts/callbacks/tensorboard
